### ISSUE TITLE
Consider moving the JS files into their own module

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-boilerplate#31]
The JavaScript assets could potentially be moved into their own module called `kapow-js`.

Given that the Sass codebase has it's own module, it makes sense for this same logic to be applied to our JavaScript files.

**Comment by davetgreen** [comment]
As discussed, we should look at switching to a more ES6 approach here; this will need to be heavily documented so that staff members of different JS confidence levels can pick up and use.

**Comment by nervewax** [comment]
I thought that we'd be treating the js in a similar way to the sass, instead of a module just all baked into the boilerplate, but globbing and file structure similar to sass?

**Comment by davetgreen** [comment]
Yeah definitely bake it in, just try and move to ES6 modules as much as we can for the bespoke stuff.

**Comment by davetgreen** [comment]
Closing off, no longer required.
