### ISSUE TITLE
Linting for JS, SCSS and PHP

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#57]
- [x] Reintroduce **linting** on `webpack` (js / scss)
  - [x] JS > https://eslint.org (airbnb preset? WPCS preset?)
  - [x] CSS > https://stylelint.io (WPCS present?)
- [ ] Introduce **checking** & **formatting** on `pre-commit` (php / js / scss)
  - [x] PHP > Husky (WPCS)
  - [ ] JS > https://prettier.io (WPCS preset?)
  - [ ] CSS > https://stylelint.io (WPCS preset?)
- [ ] Introduce more general checks and balances
  - http://danger.systems/js

**Comment by nervewax** [comment]
- [ ] Reintroduce linting (sass / js / php / wp)
  - Linting / testing stuff for kapow!
  - https://eslint.org (airbnb preset?)
  - https://prettier.io (+https://github.com/prettier/prettier-atom)
  - http://danger.systems/js

**Comment by davetgreen** [comment]
@nervewax semi-official answer re: official WP JS eslint config/ruleset is lookt at these...

- https://www.npmjs.com/package/@wordpress/eslint-plugin
- https://www.npmjs.com/package/@wordpress/eslint-config
- https://github.com/WordPress-Coding-Standards/eslint-config-wordpress
- https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress

I'll update this when I hear more
