### ISSUE TITLE
Investigate: loadCSS / loadJS

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#58]
Dave said:
>It would be worth spending some time investigating whether we can safely and reliably leverage loadCSS/loadJS to increase the performance of the initial page load.
>
>There are obvious drawbacks to this including FOUC and potential scripting issues, but some R&D should be done so that we can at least rule it out.
>
>Perhaps use a recently completed project on a staging site to get some instant feedback?

**Comment by davetgreen** [comment]
@nervewax Closing this off as I dont think it's something we should do out of the box. Needs to be on a case by case basis.
