### ISSUE TITLE
Make Kapow Invisible

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#60]
- [ ] Rm all kp / kapow prefixes from theme and plugins
- [ ] Variable rename for sass vars

**Comment by nervewax** [comment]
Potential to rename to make_do

**Comment by davetgreen** [comment]
@nervewax go for my-project/my_project as it'll be replace with the project slug when we scaffold. Just a suggestion.

**Comment by davetgreen** [comment]
This has been done, question is whether it needs moving away from `my-project` to `mkdo`
