### ISSUE TITLE
Organise inc folder

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#68]
- [x] Group functions by their purpose into their own files
- [x] ~~Debugging function~~
- [x] The following needs adding to the theme if Yoast SEO is enabled in the theme. `add_theme_support( 'yoast-seo-breadcrumbs' );`

**Comment by davetgreen** [comment]
@nervewax Debugging function is coming in a separate mu-plugin I'm writing to help us keep a centralised place for all debugging. 👍
