### ISSUE TITLE
Basic theme options

### ISSUE THREAD

**Issue by nervewax** [kapow-wp/kapow-boilerplate#74]
Found this list I made a while back, just want to check that the theme comes out of the box with all of these:

### Customizer
- [ ] Phone
- [ ] Email
- [ ] Facebook, twitter, linkedin + other common social links
- [ ] [editor-color-palette](https://richtabor.com/gutenberg-color-palettes/)

### Topbar
- [ ] Utility navigation wp menu
- [ ] Chrome theme colour  (from customizer)
- [ ] Phone number (from customizer)
- [ ] Email (from customizer)
- [ ] Social icons (from customizer)
- [ ] Call link (from customizer)

### Header
- [ ] SVG logo upload (also accept png/jpg)
- [ ] Primary navigation wp menu
- [ ] Mobile toggle (built in toggle with js and icon)
- [ ] Mobile menu opener

### Sub navigation sidebar elem  (from customizer)
- [ ] Title 
- [ ] Php to list out child pages, grandchild etc
- [ ] Mobile openable

### Lower footer
- [ ] Footer menu
- [ ] Copy text, current year, copyright symbol, all available in shortcode form

**Comment by davetgreen** [comment]
`On Hold` as we are probably going to tackle this with a more GB approach in light of: https://make.wordpress.org/core/2018/12/08/gutenberg-phase-2/
