### ISSUE TITLE
Implement Husky

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-boilerplate#79]
Implement Husky to implement pre-commit triggers for SCSS, CSS, JS and PHP formatting/linting.

Remove WP Enforcer and Composer from the repository once implemented.

**Comment by davetgreen** [comment]
FYI this file/code from WP Enforcer is really the only thing of value that we need to implement in terms of PHP checking. This is the pre-commit hook that needs to be added into the `.git` folder when the project is scaffolded/installed:

```
#!/usr/bin/env bash
#
# Commands to be run before a commit can be made to the repository
#
# @package WP Enforcer

# Determine if we have a phpcs.xml file
if [[ -f ./phpcs.xml ]]; then
	standard="--standard=./phpcs.xml"
else
	standard=''
fi

# Run PHP_CodeSniffer
echo "Running PHP_CodeSniffer..."

git diff --name-only --cached --diff-filter=ACMRTUXB | xargs vendor/bin/phpcs $standard
if [ $? != 0 ]
then
	echo "Please fix coding standards errors before committing"
	exit 1
fi
```

So, we need Husky to add a slightly more lightweight version a.k.a...

```
#!/usr/bin/env bash
# Prevent commits if PHP does not conform to Make Do PHPCS ruleset.

echo "Checking PHP passes coding standards checks..."

git diff --name-only --cached --diff-filter=ACMRTUXB | xargs phpcs --standard=./phpcs.xml --report-full=./wpcs-errors.md
if [ $? != 0 ]
then
	echo "Fix coding standards issues reported in wpcs-errors.md and re-commit!"
	exit 1
fi
```

**Comment by nervewax** [comment]
@davetgreen Yeah this looks good. I may also add in an option for `phpcbf` to auto fix any of the minor issues. Or we could just do that by default?

**Comment by davetgreen** [comment]
@nervewax I'm building that into what I'm doing now 👍

**Comment by davetgreen** [comment]
Sorted!!!

**Comment by nervewax** [comment]
🙏
